CREATE TABLE IMPIEGATO (
NOME_BATT VARCHAR(10) NOT NULL,
    INIZ_INT INTEGER,
    COGNOME VARCHAR(10) NOT NULL,
    SSN INTEGER NOT NULL,
    DATA_N DATE,
    INDIRIZZO VARCHAR(20) NOT NULL,
    SESSO CHAR(1) NOT NULL,
    STIPENDIO DECIMAL(6,2),
    SUPERSSN INTEGER,
    N_D INTEGER,
    PRIMARY KEY (SSN),
    UNIQUE (SSN),
    FOREIGN KEY (SUPERSSN) REFERENCES IMPIEGATO,
    FOREIGN KEY (D_N) REFERENCES DIPARTIMENTO);
    
CREATE TABLE DIPARTIMENTO (
	NOME_D VARCHAR(10),
    NUMERO_D INTEGER NOT NULL,
    DATA_INIZIO_DIR DATE,
    SSN_DIR INTEGER,
    PRIMARY KEY (NUMERO_D),
    UNIQUE (NUMERO_D),
    FOREIGN KEY (SSN_DIR) REFERENCES IMPIEGATO);
    
CREATE TABLE PROGETTO (
	NOME_P VARCHAR(10),
    NUMERO_P INTEGER NOT NULL,
    SEDE_P VARCHAR(10),
    NUM_D INTEGER,
    PRIMARY KEY (NUMERO_P),
    UNIQUE (NUMERO_P),
    FOREIGN KEY (NUM_D) REFERENCES DIPARTIMENTO);

CREATE TABLE LAVORA_SU (
	SSN_I INTEGER NOT NULL,
    N_P INTEGER,
    ORE TIME,
    PRIMARY KEY (SSN_I,N_P),
    FOREIGN KEY (SSN_I) REFERENCES IMPIEGATO,
    FOREIGN KEY (N_P) REFERENCES PROGETTO);
    
CREATE TABLE SEDI_DIP (
	SEDE VARCHAR(10) NOT NULL,
    SEDE_D INTEGER NOT NULL,
    PRIMARY KEY (SEDE,SEDE_D),
    FOREIGN KEY (SEDE_D) REFERENCES DIPARTIMENTO);
    
    
    